# -*- coding: utf-8 -*-
"""DIP_PROJECT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J2JEp0c2c3Q2nTIJzeyN9xucmOobD3r-

# Comparative Analysis of Image Restoration and Segmentation Techniques for Noisy Images

### Digital Image Processing Mini Project

This project investigates the restoration of noisy images using spatial filtering techniques and performs image segmentation on the restored images.

**Techniques used:**
- Gaussian noise
- Salt-and-pepper noise
- Mean filtering
- Median filtering
- Adaptive filtering
- Otsu thresholding
- Morphological operations

**Evaluation metrics:**
- Mean Squared Error (MSE)
- Peak Signal-to-Noise Ratio (PSNR)
- Structural Similarity Index (SSIM)
"""

# ============================================================
# DIGITAL IMAGE PROCESSING MINI PROJECT
# Comparative Analysis of Image Restoration and Segmentation
# ============================================================

!pip -q install scikit-image scipy pandas matplotlib opencv-python-headless

import os
import zipfile
import shutil
from pathlib import Path

import cv2
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from scipy.io import loadmat
from skimage.metrics import (
    mean_squared_error,
    peak_signal_noise_ratio,
    structural_similarity
)

from google.colab import files
from IPython.display import display

print("Libraries installed successfully!")

# ------------------------------------------------------------
# UPLOAD BSDS500 ZIP
# ------------------------------------------------------------
print("Upload your BSDS500 ZIP file.")
uploaded = files.upload()

zip_name = list(uploaded.keys())[0]

print("Dataset uploaded:", zip_name)

# EXTRACT DATASET AUTOMATICALLY

extract_path = Path("/content/BSDS500")

if extract_path.exists():
    shutil.rmtree(extract_path)

with zipfile.ZipFile(zip_name, "r") as zip_ref:
    zip_ref.extractall(extract_path)

print("Dataset extracted successfully!")

# Find actual BSDS500 root directory
def find_bsds_root(root):
    candidates = [root] + [p for p in root.rglob("*") if p.is_dir()]

    for folder in candidates:
        if (
            (folder / "images").exists()
            and (folder / "ground_truth").exists()
        ):
            return folder

    return None

BSDS_ROOT = find_bsds_root(extract_path)

if BSDS_ROOT is None:
    raise FileNotFoundError(
        "BSDS500 folders were not found. "
        "Please make sure the uploaded ZIP is the BSDS500 dataset."
    )

print("BSDS500 root folder:")
print(BSDS_ROOT)

# Check dataset
for split in ["train", "val", "test"]:

    image_folder = BSDS_ROOT / "images" / split
    gt_folder = BSDS_ROOT / "ground_truth" / split

    image_count = len(list(image_folder.glob("*.jpg")))
    gt_count = len(list(gt_folder.glob("*.mat")))

    print(
        f"{split.upper():5s} -> "
        f"{image_count} images, "
        f"{gt_count} ground-truth files"
    )

# SELECT TEST IMAGES

test_image_folder = BSDS_ROOT / "images" / "test"
test_gt_folder = BSDS_ROOT / "ground_truth" / "test"

image_gt_pairs = []

for image_path in sorted(test_image_folder.glob("*.jpg")):

    gt_path = test_gt_folder / f"{image_path.stem}.mat"

    if gt_path.exists():
        image_gt_pairs.append(
            (image_path, gt_path)
        )

# Use 30 images for practical Colab execution
N_IMAGES = 30

image_gt_pairs = image_gt_pairs[:N_IMAGES]

print("Total matching test images:", len(image_gt_pairs))

for image_path, gt_path in image_gt_pairs[:5]:
    print(image_path.name, "<->", gt_path.name)

# IMAGE PROCESSING FUNCTIONS

def read_grayscale(image_path):

    image = cv2.imread(str(image_path))

    if image is None:
        raise ValueError(
            f"Could not read image: {image_path}"
        )

    gray = cv2.cvtColor(
        image,
        cv2.COLOR_BGR2GRAY
    )

    return gray

# GAUSSIAN NOISE

def add_gaussian_noise(image, sigma=25):

    noise = np.random.normal(
        0,
        sigma,
        image.shape
    )

    noisy = image.astype(np.float32) + noise

    noisy = np.clip(
        noisy,
        0,
        255
    )

    return noisy.astype(np.uint8)

# SALT AND PEPPER NOISE

def add_salt_pepper_noise(
    image,
    amount=0.05
):

    noisy = image.copy()

    total_pixels = image.size

    number_of_pixels = int(
        amount * total_pixels
    )

    random_indices = np.random.choice(
        total_pixels,
        number_of_pixels,
        replace=False
    )

    flat = noisy.reshape(-1)

    half = number_of_pixels // 2

    # Salt
    flat[random_indices[:half]] = 255

    # Pepper
    flat[random_indices[half:]] = 0

    return noisy

# MEAN FILTER

def mean_filter(image, kernel_size=5):

    return cv2.blur(
        image,
        (kernel_size, kernel_size)
    )

# MEDIAN FILTER

def median_filter(image, kernel_size=5):

    return cv2.medianBlur(
        image,
        kernel_size
    )

# ADAPTIVE MEDIAN FILTER

def adaptive_median_filter(image):

    median_3 = cv2.medianBlur(
        image,
        3
    )

    median_5 = cv2.medianBlur(
        image,
        5
    )

    median_7 = cv2.medianBlur(
        image,
        7
    )

    result = median_3.copy()

    # Detect extreme pixels
    mask = (
        (image <= 5)
        |
        (image >= 250)
    )

    result[mask] = median_5[mask]

    # Remaining extreme pixels
    mask2 = (
        (result <= 5)
        |
        (result >= 250)
    )

    result[mask2] = median_7[mask2]

    return result

# IMAGE QUALITY METRICS

def calculate_metrics(
    original,
    restored
):

    mse = mean_squared_error(
        original,
        restored
    )

    psnr = peak_signal_noise_ratio(
        original,
        restored,
        data_range=255
    )

    ssim = structural_similarity(
        original,
        restored,
        data_range=255
    )

    return mse, psnr, ssim


print("All image-processing functions are ready!")

# DISPLAY ORIGINAL GRAYSCALE IMAGES

fig, axes = plt.subplots(
    1,
    3,
    figsize=(15, 5)
)

for ax, (image_path, gt_path) in zip(
    axes,
    image_gt_pairs[:3]
):

    image = read_grayscale(
        image_path
    )

    ax.imshow(
        image,
        cmap="gray"
    )

    ax.set_title(
        f"Original - {image_path.stem}"
    )

    ax.axis("off")

plt.tight_layout()
plt.show()

# RESTORATION DEMONSTRATION

image_path, gt_path = image_gt_pairs[0]

original = read_grayscale(
    image_path
)

# Add Gaussian noise
np.random.seed(42)

gaussian_noisy = add_gaussian_noise(
    original,
    sigma=25
)

# Add Salt-and-Pepper noise
np.random.seed(42)

sp_noisy = add_salt_pepper_noise(
    original,
    amount=0.05
)

# Gaussian restoration
gaussian_mean = mean_filter(
    gaussian_noisy,
    5
)

gaussian_median = median_filter(
    gaussian_noisy,
    5
)

gaussian_adaptive = adaptive_median_filter(
    gaussian_noisy
)

# Salt-and-Pepper restoration
sp_mean = mean_filter(
    sp_noisy,
    5
)

sp_median = median_filter(
    sp_noisy,
    5
)

sp_adaptive = adaptive_median_filter(
    sp_noisy
)

images = [
    ("Original", original),

    ("Gaussian Noise", gaussian_noisy),

    ("Gaussian + Mean", gaussian_mean),

    ("Gaussian + Median", gaussian_median),

    ("Salt-Pepper Noise", sp_noisy),

    ("SP + Mean", sp_mean),

    ("SP + Median", sp_median),

    ("SP + Adaptive Median", sp_adaptive)
]

fig, axes = plt.subplots(
    2,
    4,
    figsize=(18, 9)
)

axes = axes.ravel()

for ax, (title, image) in zip(
    axes,
    images
):

    ax.imshow(
        image,
        cmap="gray"
    )

    ax.set_title(title)

    ax.axis("off")

plt.tight_layout()
plt.show()

# RESTORATION METRICS - EXAMPLE IMAGE


results = []

methods = [

    ("Gaussian + Mean",
     gaussian_noisy,
     gaussian_mean),

    ("Gaussian + Median",
     gaussian_noisy,
     gaussian_median),

    ("Gaussian + Adaptive Median",
     gaussian_noisy,
     gaussian_adaptive),

    ("SP + Mean",
     sp_noisy,
     sp_mean),

    ("SP + Median",
     sp_noisy,
     sp_median),

    ("SP + Adaptive Median",
     sp_noisy,
     sp_adaptive)
]

for method_name, noisy, restored in methods:

    noisy_mse, noisy_psnr, noisy_ssim = calculate_metrics(
        original,
        noisy
    )

    mse, psnr, ssim = calculate_metrics(
        original,
        restored
    )

    results.append([
        method_name,
        mse,
        psnr,
        ssim
    ])

example_results = pd.DataFrame(
    results,
    columns=[
        "Method",
        "MSE",
        "PSNR",
        "SSIM"
    ]
)

display(
    example_results.round(4)
)

# COMPLETE RESTORATION EXPERIMENT

restoration_results = []

for index, (image_path, gt_path) in enumerate(
    image_gt_pairs
):

    original = read_grayscale(
        image_path
    )

    # Reproducible Gaussian noise
    np.random.seed(42 + index)

    gaussian_noisy = add_gaussian_noise(
        original,
        sigma=25
    )

    # Reproducible Salt-and-Pepper noise
    np.random.seed(42 + index)

    sp_noisy = add_salt_pepper_noise(
        original,
        amount=0.05
    )

    experiments = {

        "Gaussian": [

            ("Mean 5x5",
             mean_filter(gaussian_noisy, 5)),

            ("Median 5x5",
             median_filter(gaussian_noisy, 5)),

            ("Adaptive Median",
             adaptive_median_filter(gaussian_noisy))
        ],

        "Salt-and-Pepper": [

            ("Mean 5x5",
             mean_filter(sp_noisy, 5)),

            ("Median 5x5",
             median_filter(sp_noisy, 5)),

            ("Adaptive Median",
             adaptive_median_filter(sp_noisy))
        ]
    }

    for noise_type, methods in experiments.items():

        noisy = (
            gaussian_noisy
            if noise_type == "Gaussian"
            else sp_noisy
        )

        noisy_mse, noisy_psnr, noisy_ssim = calculate_metrics(
            original,
            noisy
        )

        for method_name, restored in methods:

            mse, psnr, ssim = calculate_metrics(
                original,
                restored
            )

            restoration_results.append([

                image_path.stem,

                noise_type,

                method_name,

                noisy_mse,

                noisy_psnr,

                noisy_ssim,

                mse,

                psnr,

                ssim
            ])


restoration_df = pd.DataFrame(

    restoration_results,

    columns=[

        "Image",

        "Noise",

        "Method",

        "Noisy MSE",

        "Noisy PSNR",

        "Noisy SSIM",

        "Restored MSE",

        "Restored PSNR",

        "Restored SSIM"
    ]
)

print("Detailed restoration results:")
display(
    restoration_df.head(10).round(4)
)

# RESTORATION SUMMARY

restoration_summary = (

    restoration_df

    .groupby(
        ["Noise", "Method"]
    )[

        [
            "Noisy MSE",
            "Noisy PSNR",
            "Noisy SSIM",

            "Restored MSE",
            "Restored PSNR",
            "Restored SSIM"
        ]

    ]

    .mean()

    .reset_index()
)

print("===== AVERAGE RESTORATION RESULTS =====")

display(
    restoration_summary.round(4)
)

# FIND BEST METHOD USING SSIM

best_methods = {}

for noise_type in restoration_summary["Noise"].unique():

    subset = restoration_summary[
        restoration_summary["Noise"]
        == noise_type
    ]

    best_row = subset.loc[
        subset["Restored SSIM"].idxmax()
    ]

    best_methods[noise_type] = (
        best_row["Method"]
    )

print("\n===== BEST RESTORATION METHODS =====")

for noise, method in best_methods.items():

    print(
        f"{noise}: {method}"
    )

# RESTORATION SSIM COMPARISON

plt.figure(figsize=(12, 6))

for noise_type in restoration_summary["Noise"].unique():

    subset = restoration_summary[
        restoration_summary["Noise"]
        == noise_type
    ]

    plt.plot(
        subset["Method"],
        subset["Restored SSIM"],
        marker="o",
        linewidth=2,
        label=noise_type
    )

plt.xlabel("Restoration Method")

plt.ylabel("Average SSIM")

plt.title(
    "Comparison of Restoration Techniques"
)

plt.xticks(
    rotation=30,
    ha="right"
)

plt.legend()

plt.grid(alpha=0.3)

plt.tight_layout()

plt.show()

# LOAD BSDS500 GROUND-TRUTH BOUNDARIES

def load_ground_truth_boundary(
    mat_path
):

    data = loadmat(
        str(mat_path),
        squeeze_me=True,
        struct_as_record=False
    )

    ground_truth = data["groundTruth"]

    ground_truth = np.asarray(
        ground_truth
    ).ravel()

    boundary_maps = []

    for item in ground_truth:

        try:

            boundary = np.asarray(
                item.Boundaries,
                dtype=np.float32
            )

            if boundary.ndim == 2:

                boundary_maps.append(
                    boundary
                )

        except Exception:
            continue

    if len(boundary_maps) == 0:

        raise ValueError(
            "No boundary annotations found."
        )

    # Consensus of human annotations
    stack = np.stack(
        boundary_maps,
        axis=0
    )

    consensus = (
        np.mean(stack, axis=0) >= 0.5
    )

    return consensus.astype(
        np.uint8
    )


print("Ground-truth boundary function ready.")

# SEGMENTATION EXAMPLE

image_path, gt_path = image_gt_pairs[0]

original = read_grayscale(
    image_path
)

# Gaussian noise
np.random.seed(42)

noisy = add_gaussian_noise(
    original,
    sigma=25
)

# Select best Gaussian restoration method
best_method = best_methods["Gaussian"]

if "Mean" in best_method:

    restored = mean_filter(
        noisy,
        5
    )

elif "Median" in best_method:

    restored = median_filter(
        noisy,
        5
    )

else:

    restored = adaptive_median_filter(
        noisy
    )


# Otsu
otsu_result = otsu_segmentation(
    restored
)

# Morphology
otsu_cleaned = morphological_cleanup(
    otsu_result
)

# Canny
canny_result = canny_segmentation(
    restored
)

# Ground truth
ground_truth = load_ground_truth_boundary(
    gt_path
)


fig, axes = plt.subplots(
    1,
    5,
    figsize=(20, 4)
)

images = [

    ("Original", original),

    ("Noisy", noisy),

    ("Restored", restored),

    ("Otsu + Morphology", otsu_cleaned),

    ("Canny", canny_result)
]

for ax, (title, image) in zip(
    axes,
    images
):

    ax.imshow(
        image,
        cmap="gray"
    )

    ax.set_title(title)

    ax.axis("off")

plt.tight_layout()
plt.show()


# Ground truth separately

plt.figure(figsize=(6, 6))

plt.imshow(
    ground_truth,
    cmap="gray"
)

plt.title(
    "BSDS500 Ground-Truth Boundary"
)

plt.axis("off")

plt.show()

# SEGMENTATION FUNCTIONS

# OTSU THRESHOLDING

def otsu_segmentation(image):

    _, binary = cv2.threshold(
        image,
        0,
        255,
        cv2.THRESH_BINARY + cv2.THRESH_OTSU
    )

    return binary

# MORPHOLOGICAL CLEANUP

def morphological_cleanup(
    binary
):

    kernel = np.ones(
        (3, 3),
        np.uint8
    )

    opened = cv2.morphologyEx(
        binary,
        cv2.MORPH_OPEN,
        kernel
    )

    cleaned = cv2.morphologyEx(
        opened,
        cv2.MORPH_CLOSE,
        kernel
    )

    return cleaned

# CANNY EDGE DETECTION

def canny_segmentation(
    image
):

    return cv2.Canny(
        image,
        50,
        150
    )


# IoU

def calculate_iou(
    prediction,
    ground_truth
):

    prediction = prediction > 0
    ground_truth = ground_truth > 0

    intersection = np.logical_and(
        prediction,
        ground_truth
    ).sum()

    union = np.logical_or(
        prediction,
        ground_truth
    ).sum()

    if union == 0:
        return 1.0

    return intersection / union

# DICE

def calculate_dice(
    prediction,
    ground_truth
):

    prediction = prediction > 0
    ground_truth = ground_truth > 0

    intersection = np.logical_and(
        prediction,
        ground_truth
    ).sum()

    denominator = (
        prediction.sum()
        + ground_truth.sum()
    )

    if denominator == 0:
        return 1.0

    return (
        2 * intersection
        / denominator
    )


print("Segmentation functions ready.")

# SEGMENTATION EVALUATION

segmentation_results = []

for index, (image_path, gt_path) in enumerate(
    image_gt_pairs
):

    original = read_grayscale(
        image_path
    )

    ground_truth = load_ground_truth_boundary(
        gt_path
    )

    for noise_type in [
        "Gaussian",
        "Salt-and-Pepper"
    ]:

        np.random.seed(
            42 + index
        )

        if noise_type == "Gaussian":

            noisy = add_gaussian_noise(
                original,
                sigma=25
            )

        else:

            noisy = add_salt_pepper_noise(
                original,
                amount=0.05
            )

        best_method = best_methods[
            noise_type
        ]

        if "Mean" in best_method:

            restored = mean_filter(
                noisy,
                5
            )

        elif "Median" in best_method:

            restored = median_filter(
                noisy,
                5
            )

        else:

            restored = adaptive_median_filter(
                noisy
            )

        # Canny
        edges = canny_segmentation(
            restored
        )

        iou = calculate_iou(
            edges,
            ground_truth
        )

        dice = calculate_dice(
            edges,
            ground_truth
        )

        segmentation_results.append([

            image_path.stem,

            noise_type,

            best_method,

            iou,

            dice
        ])


segmentation_df = pd.DataFrame(

    segmentation_results,

    columns=[

        "Image",

        "Noise",

        "Restoration",

        "IoU",

        "Dice"
    ]
)


segmentation_summary = (

    segmentation_df

    .groupby(
        ["Noise", "Restoration"]
    )[

        ["IoU", "Dice"]

    ]

    .mean()

    .reset_index()
)


print(
    "===== SEGMENTATION RESULTS ====="
)

display(
    segmentation_summary.round(4)
)

# IoU AND DICE COMPARISON

plt.figure(figsize=(10, 6))

x = np.arange(
    len(segmentation_summary)
)

width = 0.35

plt.bar(
    x - width / 2,
    segmentation_summary["IoU"],
    width,
    label="IoU"
)

plt.bar(
    x + width / 2,
    segmentation_summary["Dice"],
    width,
    label="Dice"
)

labels = [

    f"{row['Noise']}\n{row['Restoration']}"

    for _, row
    in segmentation_summary.iterrows()
]

plt.xticks(
    x,
    labels
)

plt.ylabel(
    "Score"
)

plt.ylim(
    0,
    1
)

plt.title(
    "Segmentation Performance: IoU and Dice"
)

plt.legend()

plt.grid(
    axis="y",
    alpha=0.3
)

plt.tight_layout()

plt.show()

# FINAL PROJECT SUMMARY

print("=" * 70)
print("DIGITAL IMAGE PROCESSING MINI PROJECT")
print("=" * 70)

print("\nDataset: BSDS500")
print(
    "Number of test images evaluated:",
    len(image_gt_pairs)
)

print("\n--- BEST RESTORATION METHODS ---")

for noise_type, method in best_methods.items():

    row = restoration_summary[
        (restoration_summary["Noise"] == noise_type)
        &
        (restoration_summary["Method"] == method)
    ].iloc[0]

    print(
        f"\n{noise_type}"
    )

    print(
        "Best Method:",
        method
    )

    print(
        "Average MSE:",
        round(row["Restored MSE"], 4)
    )

    print(
        "Average PSNR:",
        round(row["Restored PSNR"], 4),
        "dB"
    )

    print(
        "Average SSIM:",
        round(row["Restored SSIM"], 4)
    )


print("\n--- SEGMENTATION RESULTS ---")

display(
    segmentation_summary.round(4)
)

print("\n" + "=" * 70)
print("PROJECT EXECUTION COMPLETED")
print("=" * 70)

# SAVE RESULTS

results_folder = Path(
    "/content/DIP_Project_Results"
)

results_folder.mkdir(
    exist_ok=True
)

restoration_df.to_csv(
    results_folder / "restoration_detailed.csv",
    index=False
)

restoration_summary.to_csv(
    results_folder / "restoration_summary.csv",
    index=False
)

segmentation_df.to_csv(
    results_folder / "segmentation_detailed.csv",
    index=False
)

segmentation_summary.to_csv(
    results_folder / "segmentation_summary.csv",
    index=False
)

print("All result tables saved in:")
print(results_folder)